cmake_minimum_required(VERSION 3.20)
# Exercise real Git inputs and artifact rejection; no GPU, network or system writes.
include("${RECIPE_DIR}/source.cmake")
if(NOT TEST_DIR)
    message(FATAL_ERROR "Contract test needs a scratch directory prefix")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(TEST_DIR "${TEST_DIR}-${nonce}")
file(MAKE_DIRECTORY "${TEST_DIR}")
set(source "${TEST_DIR}/source")
pyrowave_git("${TEST_DIR}" unused clone --no-hardlinks "${APOLLO_PYROWAVE_SOURCE}" "${source}")
pyrowave_git("${TEST_DIR}" unused clone --no-hardlinks "${APOLLO_PYROWAVE_SOURCE}/Granite" "${source}/Granite")
foreach(path IN LISTS PYROWAVE_SUBMODULE_PATHS)
    # Independent clones avoid modifying the original submodule gitdir.
    pyrowave_git("${TEST_DIR}" unused clone --no-hardlinks "${APOLLO_PYROWAVE_SOURCE}/Granite/${path}" "${source}/Granite/${path}")
endforeach()
set(library "${TEST_DIR}/lib/libpyrowave-shared.so.0.6.0")
get_filename_component(original_library_dir "${APOLLO_PYROWAVE_LIBRARY}" DIRECTORY)
file(MAKE_DIRECTORY "${TEST_DIR}/lib")
file(COPY "${APOLLO_PYROWAVE_LIBRARY}" "${original_library_dir}/apollo-provenance.json" DESTINATION "${TEST_DIR}/lib")

function(check label script should_pass expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        "-DAPOLLO_PYROWAVE_SOURCE=${source}" "-DAPOLLO_PYROWAVE_LIBRARY=${library}"
        "-DPYROWAVE_BUILD_DIR=${TEST_DIR}/lib"
        ${ARGN}
        -P "${RECIPE_DIR}/${script}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(should_pass)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${label} failed: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${error}" MATCHES "${expected_error}")
        message(FATAL_ERROR "${label} did not reject for ${expected_error}: ${output}${error}")
    endif()
    message(STATUS "${label}: passed")
endfunction()

check("prepared inputs" verify-library.cmake TRUE "")
check("changed since configure" verify-library.cmake FALSE "changed since Apollo configure"
    "-DPYROWAVE_EXPECTED_HASH=old-configured-library")
check("preparation idempotence" prepare.cmake TRUE "")
file(APPEND "${source}/pyrowave.h" "\n// contaminated\n")
check("tracked codec mutation" verify-library.cmake FALSE "must be clean")
pyrowave_git("${source}" unused restore pyrowave.h)
file(WRITE "${source}/injected.hpp" "// injected include\n")
check("untracked input" prepare.cmake FALSE "must be clean")
file(REMOVE "${source}/injected.hpp")
file(WRITE "${source}/Granite/third_party/rapidjson/injected.hpp" "// optional backend injection\n")
check("optional Granite input" verify-library.cmake FALSE "must be clean")
file(REMOVE_RECURSE "${source}/Granite/third_party/rapidjson")
file(MAKE_DIRECTORY "${source}/Granite/third_party/rapidjson")
file(APPEND "${source}/Granite/third_party/volk/volk.h" "\n// contaminated\n")
check("tracked submodule mutation" verify-library.cmake FALSE "must be clean")
pyrowave_git("${source}/Granite/third_party/volk" unused restore volk.h)
file(RENAME "${source}/Granite/third_party/volk" "${TEST_DIR}/volk-backup")
file(MAKE_DIRECTORY "${source}/Granite/third_party/volk")
check("missing required submodule" verify-library.cmake FALSE "must be its own checkout")
file(REMOVE_RECURSE "${source}/Granite/third_party/volk")
file(RENAME "${TEST_DIR}/volk-backup" "${source}/Granite/third_party/volk")
pyrowave_git("${source}" unused checkout --detach "${PYROWAVE_BASE}")
check("wrong codec revision" prepare.cmake FALSE "must be its own checkout")
check("failed build" build.cmake FALSE "must be its own checkout")
if(EXISTS "${TEST_DIR}/lib/apollo-provenance.json")
    message(FATAL_ERROR "Failed build left a stale receipt")
endif()
file(COPY "${original_library_dir}/apollo-provenance.json" DESTINATION "${TEST_DIR}/lib")
pyrowave_git("${source}" unused checkout --detach "${APOLLO_PYROWAVE_PIN}")
file(APPEND "${library}" "tampered")
check("artifact mutation" verify-library.cmake FALSE "library/provenance mismatch")
file(COPY "${APOLLO_PYROWAVE_LIBRARY}" DESTINATION "${TEST_DIR}/lib")
file(REMOVE "${TEST_DIR}/lib/apollo-provenance.json")
check("unattested artifact" verify-library.cmake FALSE "Missing Pyrowave build provenance")
file(COPY "${original_library_dir}/apollo-provenance.json" DESTINATION "${TEST_DIR}/lib")
file(READ "${TEST_DIR}/lib/apollo-provenance.json" receipt)
string(JSON receipt SET "${receipt}" codec "\"${PYROWAVE_BASE}\"")
file(WRITE "${TEST_DIR}/lib/apollo-provenance.json" "${receipt}")
check("false identity receipt" verify-library.cmake FALSE "library/provenance mismatch")
file(COPY "${original_library_dir}/apollo-provenance.json" DESTINATION "${TEST_DIR}/lib")
file(READ "${TEST_DIR}/lib/apollo-provenance.json" receipt)
string(JSON receipt SET "${receipt}" recipe_sha256 "\"stale-recipe\"")
file(WRITE "${TEST_DIR}/lib/apollo-provenance.json" "${receipt}")
check("stale recipe receipt" verify-library.cmake FALSE "library/provenance mismatch")
file(COPY "${original_library_dir}/apollo-provenance.json" DESTINATION "${TEST_DIR}/lib")
check("restored inputs" verify-library.cmake TRUE "")
file(REMOVE_RECURSE "${TEST_DIR}")
