cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/source.cmake")
if(NOT APOLLO_PYROWAVE_SOURCE OR NOT PYROWAVE_BUILD_DIR)
    message(FATAL_ERROR "Pass APOLLO_PYROWAVE_SOURCE and PYROWAVE_BUILD_DIR")
endif()
get_filename_component(APOLLO_PYROWAVE_SOURCE "${APOLLO_PYROWAVE_SOURCE}" ABSOLUTE)
get_filename_component(PYROWAVE_BUILD_DIR "${PYROWAVE_BUILD_DIR}" ABSOLUTE)
cmake_path(IS_PREFIX APOLLO_PYROWAVE_SOURCE "${PYROWAVE_BUILD_DIR}" NORMALIZE nested_build)
if(nested_build)
    message(FATAL_ERROR "Keep the codec build outside its verified source directory")
endif()
file(MAKE_DIRECTORY "${PYROWAVE_BUILD_DIR}")
file(LOCK "${PYROWAVE_BUILD_DIR}/apollo-build.lock" GUARD PROCESS TIMEOUT 0)
# Remove stale evidence before any attempt; failed builds cannot reuse a receipt.
file(REMOVE "${PYROWAVE_BUILD_DIR}/apollo-provenance.json")
pyrowave_check_source("${APOLLO_PYROWAVE_SOURCE}")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}" -B "${PYROWAVE_BUILD_DIR}" -G Ninja
    "-DAPOLLO_PYROWAVE_SOURCE=${APOLLO_PYROWAVE_SOURCE}" -DCMAKE_BUILD_TYPE=Release
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Pinned Pyrowave configuration failed")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${PYROWAVE_BUILD_DIR}" --target pyrowave-shared --parallel 4
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Pinned Pyrowave build failed")
endif()
pyrowave_check_source("${APOLLO_PYROWAVE_SOURCE}")
file(SHA256 "${PYROWAVE_BUILD_DIR}/libpyrowave-shared.so.0.6.0" library_sha256)
pyrowave_recipe_hash(recipe_sha256)
file(READ "${PYROWAVE_BUILD_DIR}/apollo-toolchain.json" toolchain)
file(WRITE "${PYROWAVE_BUILD_DIR}/apollo-provenance.json"
    "{\n  \"schema\": 1,\n  \"codec\": \"${APOLLO_PYROWAVE_PIN}\",\n  \"tree\": \"${PYROWAVE_TREE}\",\n  \"granite\": \"${PYROWAVE_GRANITE_PIN}\",\n  \"recipe_sha256\": \"${recipe_sha256}\",\n  \"toolchain\": ${toolchain},\n  \"library_sha256\": \"${library_sha256}\"\n}\n")
message(STATUS "Built ${PYROWAVE_BUILD_DIR}/libpyrowave-shared.so.0.6.0 SHA256=${library_sha256}")
