cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/source.cmake")
if(NOT DEFINED APOLLO_PYROWAVE_SOURCE OR APOLLO_PYROWAVE_SOURCE STREQUAL "")
    message(FATAL_ERROR "Pass -DAPOLLO_PYROWAVE_SOURCE=<new source directory>")
endif()
get_filename_component(APOLLO_PYROWAVE_SOURCE "${APOLLO_PYROWAVE_SOURCE}" ABSOLUTE)
file(MAKE_DIRECTORY "${APOLLO_PYROWAVE_SOURCE}")
file(LOCK "${APOLLO_PYROWAVE_SOURCE}.prepare.lock" GUARD PROCESS TIMEOUT 0)

# Existing destinations are verified, never reset/cleaned or updated implicitly.
if(EXISTS "${APOLLO_PYROWAVE_SOURCE}/.git")
    pyrowave_check_source("${APOLLO_PYROWAVE_SOURCE}")
    message(STATUS "Verified existing Pyrowave ${APOLLO_PYROWAVE_PIN}; no network needed")
    return()
endif()
file(GLOB contents "${APOLLO_PYROWAVE_SOURCE}/*" "${APOLLO_PYROWAVE_SOURCE}/.*")
if(contents)
    message(FATAL_ERROR "Preparation requires a new empty directory; refusing to overwrite inputs")
endif()

pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" unused init)
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" unused remote add origin "${PYROWAVE_URL}")
# Only the public base is fetched. The local SHA is reconstructed below.
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" unused fetch --depth=1 origin "${PYROWAVE_BASE}")
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" unused checkout --detach "${PYROWAVE_BASE}")
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" unused apply --index "${CMAKE_CURRENT_LIST_DIR}/scan-fix.patch")
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" tree write-tree)
if(NOT tree STREQUAL PYROWAVE_TREE)
    message(FATAL_ERROR "Reviewed patch did not reconstruct the pinned tree")
endif()
# Hash the original raw object rather than generating timestamps/author metadata.
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" commit hash-object -t commit -w "${CMAKE_CURRENT_LIST_DIR}/scan-fix.commit")
if(NOT commit STREQUAL APOLLO_PYROWAVE_PIN)
    message(FATAL_ERROR "Reviewed commit object did not reconstruct the codec pin")
endif()
pyrowave_git("${APOLLO_PYROWAVE_SOURCE}" unused checkout --detach "${APOLLO_PYROWAVE_PIN}")
set(granite "${APOLLO_PYROWAVE_SOURCE}/Granite")
file(MAKE_DIRECTORY "${granite}")
pyrowave_git("${granite}" unused init)
pyrowave_git("${granite}" unused remote add origin "${PYROWAVE_GRANITE_URL}")
pyrowave_git("${granite}" unused fetch --depth=1 origin "${PYROWAVE_GRANITE_PIN}")
pyrowave_git("${granite}" unused checkout --detach "${PYROWAVE_GRANITE_PIN}")
foreach(path pin url IN ZIP_LISTS PYROWAVE_SUBMODULE_PATHS PYROWAVE_SUBMODULE_PINS PYROWAVE_SUBMODULE_URLS)
    pyrowave_git("${granite}" gitlink ls-tree HEAD "${path}")
    if(NOT gitlink MATCHES "160000 commit ${pin}")
        message(FATAL_ERROR "Granite gitlink ${path} disagrees with the recipe")
    endif()
    pyrowave_git("${granite}" declared_url config -f .gitmodules --get "submodule.${path}.url")
    if(NOT declared_url STREQUAL url)
        message(FATAL_ERROR "Granite submodule URL disagrees with the recipe")
    endif()
    pyrowave_git("${granite}" unused submodule update --init --depth=1 -- "${path}")
endforeach()
pyrowave_check_source("${APOLLO_PYROWAVE_SOURCE}")
message(STATUS "Prepared exact Pyrowave ${APOLLO_PYROWAVE_PIN} / tree ${PYROWAVE_TREE}")
