include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/lock.cmake")
find_package(Git REQUIRED)

function(pyrowave_recipe_hash output)
    set(hashes "")
    foreach(input IN ITEMS lock.cmake source.cmake CMakeLists.txt build.cmake scan-fix.commit scan-fix.patch)
        file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${input}" hash)
        string(APPEND hashes "${input}:${hash}\n")
    endforeach()
    string(SHA256 hash "${hashes}")
    set(${output} "${hash}" PARENT_SCOPE)
endfunction()

function(pyrowave_git directory output)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${directory}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE value ERROR_VARIABLE error
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Pyrowave git ${ARGN} failed in ${directory}: ${error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(pyrowave_check_checkout directory pin)
    pyrowave_git("${directory}" head rev-parse HEAD)
    pyrowave_git("${directory}" top rev-parse --show-toplevel)
    file(REAL_PATH "${directory}" expected_top)
    if(NOT head STREQUAL pin OR NOT top STREQUAL expected_top)
        message(FATAL_ERROR "Pyrowave source ${directory} must be its own checkout at ${pin}; got ${head}")
    endif()
    # Include ignored/untracked files: injected headers or optional Granite modules
    # can otherwise change the build while the advertised Git identity stays clean.
    pyrowave_git("${directory}" dirty status --porcelain --untracked-files=all --ignored)
    if(ARGC GREATER 2)
        # Pyrowave has no Granite gitlink; the recipe supplies this one directory.
        string(REGEX REPLACE "(\n|^)(\\?\\?|!!) Granite/[^\n]*" "" dirty "${dirty}")
        string(STRIP "${dirty}" dirty)
    endif()
    if(NOT dirty STREQUAL "")
        message(FATAL_ERROR "Pyrowave source ${directory} must be clean, including untracked inputs: ${dirty}")
    endif()
endfunction()

function(pyrowave_check_source source)
    pyrowave_check_checkout("${source}" "${APOLLO_PYROWAVE_PIN}" ALLOW_GRANITE)
    pyrowave_git("${source}" tree rev-parse HEAD^{tree})
    if(NOT tree STREQUAL PYROWAVE_TREE)
        message(FATAL_ERROR "Pyrowave tree mismatch")
    endif()
    pyrowave_check_checkout("${source}/Granite" "${PYROWAVE_GRANITE_PIN}")
    # Git status overlooks files placed inside an uninitialized gitlink. Some
    # Granite CMake branches use EXISTS, so even an untracked header can alter
    # the target graph. Only the explicitly required submodules may be populated.
    pyrowave_git("${source}/Granite" entries ls-tree -r HEAD)
    string(REPLACE "\n" ";" entries "${entries}")
    foreach(entry IN LISTS entries)
        if(entry MATCHES "^160000 commit [0-9a-f]+\t(.+)$")
            set(path "${CMAKE_MATCH_1}")
            if(NOT path IN_LIST PYROWAVE_SUBMODULE_PATHS)
                file(GLOB contents "${source}/Granite/${path}/*" "${source}/Granite/${path}/.*")
                if(contents)
                    message(FATAL_ERROR "Granite must be clean: unsupported optional input ${path}")
                endif()
            endif()
        endif()
    endforeach()
    foreach(path pin IN ZIP_LISTS PYROWAVE_SUBMODULE_PATHS PYROWAVE_SUBMODULE_PINS)
        pyrowave_check_checkout("${source}/Granite/${path}" "${pin}")
    endforeach()
endfunction()
