cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/source.cmake")
pyrowave_check_source("${APOLLO_PYROWAVE_SOURCE}")
if(NOT EXISTS "${APOLLO_PYROWAVE_LIBRARY}")
    message(FATAL_ERROR "Build the pinned codec using cmake/dependencies/pyrowave/build.cmake")
endif()
get_filename_component(library_dir "${APOLLO_PYROWAVE_LIBRARY}" DIRECTORY)
if(NOT EXISTS "${library_dir}/apollo-provenance.json")
    message(FATAL_ERROR "Missing Pyrowave build provenance; run the tracked build.cmake recipe")
endif()
file(READ "${library_dir}/apollo-provenance.json" provenance)
string(JSON schema GET "${provenance}" schema)
string(JSON codec GET "${provenance}" codec)
string(JSON tree GET "${provenance}" tree)
string(JSON granite GET "${provenance}" granite)
string(JSON hash GET "${provenance}" library_sha256)
string(JSON recipe GET "${provenance}" recipe_sha256)
pyrowave_recipe_hash(expected_recipe)
file(SHA256 "${APOLLO_PYROWAVE_LIBRARY}" APOLLO_PYROWAVE_LIBRARY_SHA256)
if(NOT schema EQUAL 1 OR NOT codec STREQUAL APOLLO_PYROWAVE_PIN
        OR NOT tree STREQUAL PYROWAVE_TREE OR NOT granite STREQUAL PYROWAVE_GRANITE_PIN
        OR NOT hash STREQUAL APOLLO_PYROWAVE_LIBRARY_SHA256 OR NOT recipe STREQUAL expected_recipe)
    message(FATAL_ERROR "Pyrowave library/provenance mismatch; rebuild with the tracked recipe")
endif()
if(DEFINED PYROWAVE_EXPECTED_HASH AND NOT APOLLO_PYROWAVE_LIBRARY_SHA256 STREQUAL PYROWAVE_EXPECTED_HASH)
    message(FATAL_ERROR "Pyrowave library changed since Apollo configure; reconfigure Apollo")
endif()
find_program(PYROWAVE_READELF readelf REQUIRED)
execute_process(COMMAND "${PYROWAVE_READELF}" -d "${APOLLO_PYROWAVE_LIBRARY}"
    RESULT_VARIABLE result OUTPUT_VARIABLE dynamic)
if(NOT result EQUAL 0 OR NOT dynamic MATCHES "SONAME[^\n]*\\[libpyrowave-shared.so.0\\]")
    message(FATAL_ERROR "Pyrowave library must have the reviewed libpyrowave-shared.so.0 SONAME")
endif()
get_filename_component(library_name "${APOLLO_PYROWAVE_LIBRARY}" NAME)
if(NOT library_name STREQUAL "libpyrowave-shared.so.0.6.0")
    message(FATAL_ERROR "Pass the recipe's real libpyrowave-shared.so.0.6.0 file")
endif()
