#version 450
layout(local_size_x = 16, local_size_y = 16) in;
layout(set = 0, binding = 0) uniform sampler2D snapshot_image;
layout(set = 0, binding = 1, std430) buffer Result { uint invalid; } result;
void main() {
  ivec2 p = ivec2(gl_GlobalInvocationID.xy);
  if (all(lessThan(p, textureSize(snapshot_image, 0))) &&
      texelFetch(snapshot_image, p, 0).a != 1.0) {
    atomicOr(result.invalid, 1);
  }
}
